services:
  docs:
    image: mjk_local_docs
    container_name: mjk_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./mjk:/app/mjk:z
    ports:
      - '9000:9000'
    command: /start-docs
